"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowUpRight, Check, Clock3, MessageSquare, X } from "lucide-react";

type Offer = { id:string; buyer_id:string; seller_id:string; amount:number; message?:string|null; status:string; expires_at?:string|null; listing?:{title:string;slug:string;price:number}; buyer?:{name:string}; seller?:{name:string} };
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n||0);
export default function OffersPage(){
 const [offers,setOffers]=useState<Offer[]>([]); const [viewerId,setViewerId]=useState(""); const [loading,setLoading]=useState(true);
 const act=async(offerId:string,action:string)=>{const r=await fetch("/api/offers/action",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({offerId,action})});if(r.ok)setOffers(x=>x.map(o=>o.id===offerId?{...o,status:action==="accept"?"accepted":action==="decline"?"declined":action==="withdraw"?"withdrawn":o.status}:o));else{const e=await r.json().catch(()=>({}));alert(e.error||"Offer action failed")}};
 useEffect(()=>{fetch("/api/offers").then(r=>r.json()).then(x=>{setOffers(x.offers||[]);setViewerId(x.viewerId||"")}).finally(()=>setLoading(false));},[]);
 return <div className="mx-auto max-w-6xl px-5 py-10 lg:px-8"><div className="field-label">Deal desk / offers</div><h1 className="display-lg mt-2">Conversations that can become transactions.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-ink-soft">Offers are first-class deal objects. Every amount, counter, expiry, and acceptance is traceable instead of disappearing inside a chat thread.</p><div className="mt-8 doc-card divide-y divide-hairline overflow-hidden">{loading?<div className="p-10">Loading offer ledger…</div>:offers.length?offers.map(o=><div key={o.id} className="p-5"><div className="flex flex-col gap-4 md:flex-row md:items-center"><div className="flex h-11 w-11 items-center justify-center rounded-md border border-hairline"><MessageSquare size={16}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-display text-lg font-bold">{o.listing?.title||"Listing"}</h2><span className="case-stamp case-stamp--pending">{o.status}</span></div><p className="mt-1 text-sm text-ink-soft">{o.message||"No note attached."}</p></div><div><div className="micro-kicker">Offer</div><div className="font-display text-xl font-bold">{money(o.amount)}</div></div><div><div className="micro-kicker">Expires</div><div className="mt-1 flex items-center gap-1 text-xs"><Clock3 size={12}/>{o.expires_at?new Date(o.expires_at).toLocaleDateString():"—"}</div></div><div className="flex gap-2"><Link className="card-arrow" href={`/projects/${o.listing?.slug||""}`}><ArrowUpRight size={15}/></Link>{o.status==="sent"&&o.seller_id===viewerId && <><button onClick={()=>act(o.id,"accept")} className="btn-primary px-3"><Check size={13}/> Accept</button><button onClick={()=>act(o.id,"decline")} className="btn-secondary px-3"><X size={13}/> Decline</button></>}{o.status==="sent"&&o.buyer_id===viewerId&&<button onClick={()=>act(o.id,"withdraw")} className="btn-secondary px-3"><X size={13}/> Withdraw</button>}{o.status==="accepted"&&<span className="case-stamp case-stamp--verified">accepted</span>}</div></div></div>):<div className="p-12 text-center text-sm text-ink-soft">No offers yet. When a buyer makes a serious move, it lands here.</div>}</div></div>
}
